agv:
 #publish all joint states
  joint_state_controller:
     type: joint_state_controller/JointStateController
     publish_rate: 50

  #position controllers
  base_steer_joint_controller:
    type: effort_controllers/JointPositionController
    joint: base_steer_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

  steer_to_roll_joint_controller:
    type: effort_controllers/JointPositionController
    joint: steer_to_roll_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

  forklift_prismatic_joint_controller:
    type: effort_controllers/JointPositionController
    joint: forklift_prismatic_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}



